---
- hosts: all
  become: true
  vars:
    file_name: "server.js"
  tasks:
    - name: Copy application file to server
      copy:
        src: "{{ file_name }}"
        dest: "/home/{{app_user}}/app/{{ file_name }}"
    - name: Start application
      command:
        cmd: "pm2 start /home/{{app_user}}/app/{{ file_name }} --name myapp"
