---
- hosts: all
  become: true
  tasks:
    - name: Create folder
      file:
        path: /etc/myapp
        state: directory
        mode: "0755"
    - name: Copy JSON
      copy:
        content: "{'prod': {{prod}}, 'hostname': '{{inventory_hostname}}'}"
        dest: /etc/myapp/config.json
        force: true
