---
- hosts: all
  become: true
  vars:
    config:
      prod: "{{ prod }}"
      hostname: "{{ inventory_hostname }}"
  tasks:
    - name: Create folder
      file:
        path: /etc/myapp
        state: directory
        mode: "0755"
    - name: Copy JSON
      copy:
        content: "{{ config | to_json }}"
        dest: /etc/myapp/config.json
        force: true

    - name: install packages
      apt:
        name: "{{ item }}"
        state: latest
      loop:
        - jq
