---
- hosts: all
  become: true
  tasks:
    - name: Check if file exists
      stat:
        path: /etc/myapp/config.json
      register: file_exists
      failed_when: file_exists.stat.exists == false

    - name: Establish hostname
      block:
        - name: Verify hostname
          command:
            cmd: jq ".hostname" /etc/myapp/config.json
          register: hostname_result
          failed_when: hostname_result.stdout != "\"{{inventory_hostname}}\""
      rescue:
        - name: Update hostname if incorrect
          template:
            src: templates/config.j2
            dest: /etc/myapp/config.json
            force: true

    - name: Verify prod value
      command:
        cmd: jq ".prod" /etc/myapp/config.json
      register: prod_result
      failed_when: prod_result.stdout != "\"true\""