---
- hosts: all
  become: true
  tasks:
    - name: update repository index
      apt:
        update_cache: yes

    - name: install packages
      apt:
        name: "{{ item }}"
        state: latest
      loop:
        - apache2
        - libapache2-mod-php

    - name: run JD's custom Python script
      my_test:
        name: "hello"
        new: true
      register: jd_response

    - name: Do we need a reboot?
      stat:
        path: /var/run/reboot-required
        get_checksum: no
      register: reboot_required_file

    - name: Reboot if needed
      reboot:
      when: reboot_required_file.stat.exists == true

    - name: Remove dependencies that aren't needed
      apt:
        autoremove: yes
