---
- hosts: all
  become: true
  vars:
    file_name: "test.json"
  tasks:
    - name: Create application user
      user:
        name: "{{app_user}}"
        system: true
        shell: /bin/bash
        home: "/home/{{app_user}}"
        create_home: yes

    - name: Create application directory
      file:
        path: "/home/{{app_user}}/app"
        state: directory
        owner: "{{app_user}}"
        group: "{{app_user}}"
        mode: "0755"

    - name: Copy application file to server
      copy:
        src: "{{ file_name }}"
        dest: "/home/{{app_user}}/app/{{ file_name }}"
        force: no

    - name: Call custom python script
      my_test:
        name: "Ansible"
        new: true
        path: "/home/{{app_user}}/app/{{ file_name }}"
      register: my_test_result

    - name: Display installed Node.js version
      debug:
        msg: "Custom module result: {{ my_test_result }}"
